title: Lucas Oliveira
email: hi@lucasprag.com
description: >-
  Pragmatic programmer with more than 6 years of experience with Ruby, JavaScript and PHP.
  I like Ruby a lot, but I also like some others languages such as JavaScript and Elixir.
baseurl: ""
url: ""
twitter_username: lucasprag
github_username:  lucasprag

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
